#!/bin/bash

PICOCTF_HOME=${PICOCTF_HOME:-'/home/vagrant/'}

if [ ! -d "$PICOCTF_HOME" ]; then
	echo "$PICOCTF_HOME does not exist."
	echo "Please set PICOCTF_HOME to the picoCTF-Platform-2 directory"
	exit 1
fi

# Transpile the CoffeeScript files
echo "Transpiling Coffeescript"
coffee -c -o ${PICOCTF_HOME}/web/js/ ${PICOCTF_HOME}/web/coffee/

# Shutdown the server
echo "Shutting down nginx"
sudo service nginx stop

# Clean out the old files
echo "Cleaning up old files"
sudo rm -rf /srv/http/ctf/*

echo "Generating web with Jekyll"
cd ${PICOCTF_HOME}/web
sudo jekyll build

echo "Copying files to server"
#sudo cp -r ${PICOCTF_HOME}/web/* /srv/http/ctf/
mkdir -p ${PICOCTF_HOME}/problem_static
sudo cp -r ${PICOCTF_HOME}/problem_static /srv/http/ctf/problem-static

# Make sure everything is in UNIX format.
sudo dos2unix -q /srv/http/ctf/*.html

# Start the server
echo "Restarting the server"
sudo service nginx start

# Clear the cache
echo "Clearing the API cache"
${PICOCTF_HOME}/api/api_manager.py database clear cache

#Start picoCTF API
echo "Starting the picoCTF API"
tmux kill-session -t picoapi 2> /dev/null
tmux new-session -s picoapi -d "cd ${PICOCTF_HOME}/api && python3 run.py"
